version: '3.8'

services:
  web:
    build: .
    # 0.0.0.0:8000 all valid addresses on the local machine
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/code

    ports:

      - 8000:8000

    depends_on:
      - db

  db:
    image: postgres:12

    environment:
      - POSTGRES_PASSWORD=postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:

  postgres_data:



